version: '3'

services:
  redis:
    container_name: redis
    image: 'redis'
    networks:
      - node-network

  node-app:
    build: .
    image: node-app
    environment:
      - PORT=3001
      - REDIS_HOST=redis
    ports:
      - '3001:3001'
    networks:
      - node-network
    command: yarn start

  nginx:
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - node-app
    networks:
      - node-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  node-network:
    driver: bridge
