version: '3'

services:
  redis:
    container_name: redis
    image: 'redis'

  node-app:
    build: .
    image: node-app
    environment:
      - PORT=3001
      - REDIS_HOST=redis
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/node-app
